#ifndef TPM_BASE_TYPES_H
#define TPM_BASE_TYPES_H

#include <stdbool.h>
#include <stdint.h>

/*******************************
 *  SIGNED AND UNSIGNED TYPES
 *******************************/

// 8-bit
typedef uint8_t UINT8;
typedef uint8_t BYTE;
typedef int8_t  INT8;

// bool
typedef int BOOL;

// 16-bit
typedef uint16_t UINT16;
typedef int16_t  INT16;

// 32-bit
typedef uint32_t UINT32;
typedef int32_t  INT32;

// 64-bit
typedef uint64_t UINT64;
typedef int64_t  INT64;

/*******************************
 *  LOGIC VALUES
 *******************************/

#define TRUE  1
#define FALSE 0
#define YES   1
#define NO    0
#define SET   1
#define CLEAR 0

/************************************************
 *  MISCELLANEOUS TYPES (backward compatibility)
 ************************************************/

typedef UINT32 TPM_ALGORITHM_ID;

/* Modifier indicator type */
typedef UINT32 TPM_MODIFIER_INDICATOR;

/* Authorization size parameter in a command */
typedef UINT32 TPM_AUTHORIZATION_SIZE;

/* Parameter size parameter in a command */
typedef UINT32 TPM_PARAMETER_SIZE;

/* Key size in octets */
typedef UINT16 TPM_KEY_SIZE;

/* Key size in bits */
typedef UINT16 TPM_KEY_BITS;

/***************************************************************
 *  TPM_SPEC CONSTANTS (values readable by TPM2_GetCapability())
 ***************************************************************/

/* Family identifier: ASCII "2.0" with null terminator */
#define TPM_SPEC_FAMILY 0x322E3000u /* "2.0\0" in ASCII (little-endian) */

/* Level number of the specification */
#define TPM_SPEC_LEVEL 0u

/* Version number of the spec (001.83 * 100 = 183) */
#define TPM_SPEC_VERSION 183u

/* Year of the spec version */
#define TPM_SPEC_YEAR 2024u

/* Day of year of the spec version (January 25 = 25) */
#define TPM_SPEC_DAY_OF_YEAR 25u

/*********************************
 *  MISCELLANEOUS CONSTANT VALUES
 *********************************/

/* Value used to differentiate TPM-generated structures from non-TPM structures
 * 0xFF 'TCG' → bytes: FF 54 43 47
 */
#define TPM_GENERATED_VALUE 0xFF544347u

/* Maximum number of bits that may be generated by an instantiation of the
 * deterministic pseudo-random bit generator (DRBG).
 */
#define TPM_MAX_DERIVATION_BITS 8192u

#endif /* TPM_BASE_TYPES_H */
