######################################
#### Build QEMU via Meson + Ninja ####
######################################
cd ..
mkdir qemu/build
cd qemu/build/
# Configure Meson, get host architecture and OS, ...
../configure --target-list=arm-softmmu
# Build QEMU
make

######################################
#### Build firmware via Makefile  ####
######################################
cd ../../firmware
# Compile and link into .elf file to flash
make all
# Run QEMU binary generated by QEMU build to load firmware
make qemu_start
