#ifndef HW_ARM_NXPS32K3X8EVB_H
#define HW_ARM_NXPS32K3X8EVB_H

#define NXPS32K3X8_IRQ_NUM 240
#define NXPS32K3X8_STD_CLK 48*1000*1000

// Defining ITCM_ADDRESS and SIZE
#define ITCM_BASE_ADDRESS   0X00000000
#define ITCM0_OFFSET        (0    * 1024)

#define ITCM_BLOCK_SIZE     (64   * 1024)
#define ITCM_NUM            1

#define ITCM0               (ITCM_BASE_ADDRESS + ITCM0_OFFSET)
#define ITCM_SIZE           (ITCM_BLOCK_SIZE + ITCM_NUM)

// Defining PFLASH_ADDRESS and SIZE
#define PFLASH_BASE_ADDRESS 0x00400000
#define PBLOCK0_OFFSET      (0    * 1024)
#define PBLOCK1_OFFSET      (2048 * 1024)
#define PBLOCK2_OFFSET      (4096 * 1024)
#define PBLOCK3_OFFSET      (6144 * 1024)

#define PFLASH_BLOCK_SIZE   (2048 * 1024)
#define PFLASH_NUM          4
#define PFLASH_SIZE         (PFLASH_NUM * PFLASH_BLOCK_SIZE)

#define PFLASH_BLOCK0       (FLASH_BASE_ADDRESS + BLOCK0_OFFSET)
#define PFLASH_BLOCK1       (FLASH_BASE_ADDRESS + BLOCK1_OFFSET)
#define PFLASH_BLOCK2       (FLASH_BASE_ADDRESS + BLOCK2_OFFSET)
#define PFLASH_BLOCK3       (FLASH_BASE_ADDRESS + BLOCK3_OFFSET)
// Defining DATA_FLASH_BASE_ADDRESS and SIZE
#define DFLASH_BASE_ADDRESS 0x10000000
#define DBLOCK_OFFSET       (0    * 1024)

#define DFLASH_BLOCK_SIZE   (256  * 1024)
#define DFLASH_NUM          1
#define DFLASH_SIZE         (DFLASH_BLOCK_SIZE * DFLASH_NUM)

// Defining SRAM_ADDRESS and SIZE
#define SRAM_BASE_ADDRESS   0x20400000
#define SRAM0_OFFSET        (0   * 1024)
#define SRAM1_OFFSET        (256 * 1024)
#define SRAM2_OFFSET        (512 * 1024)

#define SRAM_BLOCK_SIZE     (256 * 1024)    // 256 KB
#define SRAM_NUM            3
#define SRAM_SIZE           (SRAM_BLOCK_SIZE * SRAM_NUM)

#define SRAM0               (SRAM_BASE_ADDRESS + SRAM0_OFFSET)
#define SRAM1               (SRAM_BASE_ADDRESS + SRAM1_OFFSET)
#define SRAM2               (SRAM_BASE_ADDRESS + SRAM2_OFFSET)

//UART
#define LPUART_BASE_ADDRESS 0x40328000
#define LPUART0_OFFSET      (0    * 1024)

#define LPUART0 (LPUART_BASE_ADDRESS + LPUART0_OFFSET)

#define UART_SIZE           (16    * 1024)

#define LPUART0_TRANSMIT_INTERRUPT      141




#endif
